count = int(input())
str1 = ("   _~_    ")
str2 = ("  (o o)   ")
str3 = (" /  V  \  ")
str4 = ("/(  _  )\ ")
str5 = ("  ^^ ^^   ")
print(str1*count)
print(str2*count)
print(str3*count)
print(str4*count)
print(str5*count)
